import config from 'config';
export const externalLinks = {
  carbonHomepage: '#',
  blog: '#',
  faq: '#',
  analytics: '#',
  x: '#',
  youtube: '#',
  discord: '#',
  telegram: '#',
  techDocs: '#',
  litePaper: '#',
  whitepaper: '#',
  simulatorRepo: '#',
  interactiveSim: '#',
  duneDashboard: '#',
  roiLearnMore: '#',
  treasuryGov: '#',
  terms: config.appUrl + '/terms',
  privacy: config.appUrl + '/privacy',
  whatIsOverlapping: '#',
};
